# Generated by Django 4.2 on 2024-05-13 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecategory',
            name='image',
            field=models.ImageField(upload_to='media/course-categories/images/'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('rating', models.CharField(max_length=20)),
                ('currently_enrolled', models.IntegerField()),
                ('price', models.IntegerField()),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=120)),
                ('duration', models.DurationField()),
                ('image', models.ImageField(upload_to='media/course/images/')),
                ('is_paid', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursecategory')),
            ],
        ),
    ]
