# Generated by Django 4.2 on 2024-05-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_enroled'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lessons',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
