# Generated by Django 4.2 on 2024-05-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroled',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'pending'), ('complete', 'complete'), ('failed', 'failed')], default='complete', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enroled',
            name='ref_no',
            field=models.CharField(default='en_001_0000021246547687', max_length=1000),
            preserve_default=False,
        ),
    ]
