# Generated by Django 4.2 on 2024-05-15 02:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 15, 2, 52, 26, 996476, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
