# Generated by Django 4.2 on 2024-05-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('staff', 'staff'), ('student', 'student'), ('instructor', 'instructor')], default='student', max_length=100),
        ),
    ]
